[target.armv7-unknown-linux-gnueabihf]
linker = "/home/tqm/Rust/arm-buildroot-linux-gnueabihf_sdk-buildroot/bin/arm-buildroot-linux-gnueabihf-gcc"
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"
[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_SYSROOT_DIR = { value = "/home/tqm/Rust/arm-buildroot-linux-gnueabihf_sdk-buildroot/arm-buildroot-linux-gnueabihf/sysroot", force = true }
PKG_CONFIG_PATH = { value = "/home/tqm/Rust/arm-buildroot-linux-gnueabihf_sdk-buildroot/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/pkgconfig:/home/tqm/Rust/arm-buildroot-linux-gnueabihf_sdk-buildroot/arm-buildroot-linux-gnueabihf/sysroot/usr/share/pkgconfig:/home/tqm/Rust/arm-buildroot-linux-gnueabihf_sdk-buildroot/arm-buildroot-linux-gnueabihf/sysroot/lib/pkgconfig", force = true }